# Generated by Django 2.1.4 on 2019-01-24 21:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Cash', max_length=128)),
                ('description', models.CharField(max_length=512, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(default='BDT', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('user', models.CharField(default='Anonymous', max_length=128)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 1, 24, 21, 32, 4, 981370, tzinfo=utc))),
                ('account', models.CharField(default='Cash', max_length=128)),
                ('type', models.CharField(default='debit', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('remark', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_transaction', models.CharField(default='none', max_length=128)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
