# Generated by Django 2.1.4 on 2019-01-24 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 21, 33, 24, 288365, tzinfo=utc)),
        ),
    ]
